controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\AccueilController

live_component:
    resource: '@LiveComponentBundle/Resources/config/routing/live_component.xml'